### PR TITLE
Infer repo/directory structure as well as upstream branch name

### PR DESCRIPTION
**Pull request by joshmcgrath08**

### CODE REVIEW

**Comment by rkta** [comment]
```
% git clone https://github.com/joshmcgrath08/multigitstatus.git
Cloning into 'multigitstatus'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 58 (delta 24), reused 45 (delta 15), pack-reused 0
Unpacking objects: 100% (58/58), 9.03 KiB | 271.00 KiB/s, done.
% cd multigitstatus
% git checkout infer_repo_and_upstream_pr
Branch 'infer_repo_and_upstream_pr' set up to track remote branch 'infer_repo_and_upstream_pr' from 'origin'.
Switched to a new branch 'infer_repo_and_upstream_pr'
% bash bin/multigitstatus
fatal: ambiguous argument '(HEAD..remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by joshmcgrath08** [comment]
@rkta Thanks for trying it out and providing reproduction steps when it failed. My hypothesis is that one of the sibling directories of the cloned repo is in detached head mode. (If this hypothesis is correct: if you run `bash bin/multigitstatus .` instead of `bash bin/multigitstatus` it should monitor the current directory instead of popping up one level before trying to monitor.) I was able to replicate your output with the following:

```
# Create a new directory, and clone 2 copies of repo into it
$ mkdir multigitstatustest
$ cd multigitstatustest/
$ git clone -q https://github.com/joshmcgrath08/multigitstatus.git multigitstatus
$ git clone -q https://github.com/joshmcgrath08/multigitstatus.git multigitstatus2
$ cd multigitstatus
$ git checkout infer_repo_and_upstream_pr

# Run once (as opposed to auto-updating)
$ env MULTIGITSTATUS_DO_RUN=true bash bin/multigitstatus
Multigitstatus for /home/josh/multigitstatustest

./multigitstatus2: CLEAN
./multigitstatus: CLEAN

# Go into detached head mode in second repo
$ cd ../multigitstatus2
$ git checkout c539fadef8494ed74c41749498def10bbbdfc5b1
Note: switching to 'c539fadef8494ed74c41749498def10bbbdfc5b1'.
...

# Go back to first repo and run again
$ cd ../multigitstatus
$ env MULTIGITSTATUS_DO_RUN=true bash bin/multigitstatus
Multigitstatus for /home/josh/multigitstatustest

fatal: ambiguous argument '(HEAD..remotes/origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

All of that said, let me also put something in place to handle detached head mode.

> ```
> % git clone https://github.com/joshmcgrath08/multigitstatus.git
> Cloning into 'multigitstatus'...
> remote: Enumerating objects: 58, done.
> remote: Counting objects: 100% (58/58), done.
> remote: Compressing objects: 100% (30/30), done.
> remote: Total 58 (delta 24), reused 45 (delta 15), pack-reused 0
> Unpacking objects: 100% (58/58), 9.03 KiB | 271.00 KiB/s, done.
> % cd multigitstatus
> % git checkout infer_repo_and_upstream_pr
> Branch 'infer_repo_and_upstream_pr' set up to track remote branch 'infer_repo_and_upstream_pr' from 'origin'.
> Switched to a new branch 'infer_repo_and_upstream_pr'
> % bash bin/multigitstatus
> fatal: ambiguous argument '(HEAD..remotes/origin/master': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> ```

**Comment by joshmcgrath08** [comment]
Now when I run through the same steps I outlined above (checking out a slightly different verison), I get the following output:

```
josh@josh-ThinkPad-X1C-5th-W10DG:~/multigitstatustest/multigitstatus$ env MULTIGITSTATUS_DO_RUN=true bash bin/multigitstatus
Multigitstatus for /home/josh/multigitstatustest

./multigitstatus2: BEHIND by 4 COMMITS

Commits on origin/main but not HEAD:
c539fad Add some content tot README
7d7c0dd Handle case of ahead and behind
9f31935 Fix handling of ahead/behind commits
06bb212 Add header to screen

./multigitstatus: CLEAN
```

**Comment by rkta** [comment]
You were right, one repo was in detached head. Applying f842c98 fixed
this. And providing `.` worked also.

Now I got another error:
```
% bash bin/multigitstatus
% Could not determine upstream in /home/kt/code/AStyle
% cd ../AStyle
% g remote -vv
%

```

Should I open an issue for that?

I will try the script a bit tomorrow(CET) and report further problems.

**Comment by joshmcgrath08** [comment]
@rkta Great, thanks. At least this error was one that my script was throwing. Let me relax it so that it's a warning instead of exiting the script;

**Comment by rkta** [comment]
Just saw it in the code and wanted to suggest this ;) Thanks

**Comment by rkta** [comment]
One more thing, this branch fails on directories containing a space in their name.

One thing is line 89: Should use `find [...] -print0 | xargs -0`.
And I suppose, line 93: This assigns an array to a string, names with spaces will be two words afterwards. Then in line 102 you iterate over the string. Guess it breaks there. 

HTH :)

**Comment by joshmcgrath08** [comment]
@rkta I had run into some annoying issues when trying to get spaces in paths working as intended, so I punted on it.

I just pushed a commit that will handle spaces in paths (both inferred and passed as arguments). Thanks again for your helpful feedback.

**Comment by joshmcgrath08** [comment]
(And I ended up not using arrays because it's not clear to me how portable they are across various platforms.)

**Comment by rkta** [comment]
> (And I ended up not using arrays because it's not clear to me how portable they are across various platforms.)

As this is bash, arrays are fine: 
https://www.gnu.org/software/bash/manual/html_node/Arrays.html

Or isn't this intended to be bash and you just have the wrong shebang? 

Your current solution will fail on names containing newlines (which is
an insane, but legal idea).

**Comment by joshmcgrath08** [comment]
It is intended to be a bash script. I think that I was mixing up the newness of associative arrays with regular arrays.

I am okay with newlines in file names not being supported :)

Among other places, I want this to work in the Linux subsystem in Windows, which doesn't come with `watch` installed by default (hence my strange use of `less`), so I have been very cautious about using anything but the most standard features of bash, common programs, etc. Perhaps I went a bit overboard.

Thanks again for the help. Things are looking a lot better because of your input.

I'm going to get this merged now.

**Comment by rkta** [comment]
> Among other places, I want this to work in the Linux subsystem in Windows,
> which doesn't come with `watch` installed by default (hence my strange use of
> `less`), so I have been very cautious about using anything but the most
> standard features of bash, common programs, etc. Perhaps I went a bit
> overboard.

This is important information, you should add it to the README so that
future contributors be warned.

> Thanks again for the help. Things are looking a lot better because of your
> input.

Cheers! ;)

**Pull request merged**
